# Generated by Django 5.0.4 on 2024-04-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='currency',
            field=models.URLField(default='EUR', max_length=255),
        ),
    ]
