# Generated by Django 5.0.4 on 2024-04-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=models.CharField(default='EUR', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
